services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: pos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    env_file:
      - .env
